### ISSUE TITLE
popup menu not aligned

### ISSUE THREAD

**Issue by davidhuang1550** [davidhuang1550/NestFinder#20]
<img width="289" alt="screen shot 2017-05-16 at 7 57 09 pm" src="https://cloud.githubusercontent.com/assets/22035024/26133607/6528ecdc-3a76-11e7-907f-7c86cf65d6c3.png">

@Gammaalpha hey mind working on this issue? this needs margins so it dosnt stick to the side and comes out of alittle bit when clicking on the three dot icon

this build is in a detailspageWIP branch

**Comment by Gammaalpha** [comment]
can you show me an example of how you want this or give me more details as to how it should behave?

**Comment by davidhuang1550** [comment]
https://i.stack.imgur.com/bhVEt.jpg

**Comment by Gammaalpha** [comment]
Pop up menu alignment corrected and pull request created.
